### ISSUE TITLE
Failed to edit a variable

### ISSUE THREAD

**Issue by f3rran** [nasa8x/v-markdown-editor#17]
Hello,
I'm implementing that nice tool to a project. At the creation form that library works nice with the variable empty. But at the edition form the variable which stores the content doesn't recieve the changes ( i tried the onchange function).
What can I do?

`<markdown-editor :options="options" v-model="description" theme="success"  @change="onChange" preview-mode="true"></markdown-editor>`

Thanks

**Comment by nasa8x** [comment]
Have you defined a `description`?
{
data(){
return {
description:''
}
}
}

**Comment by f3rran** [comment]
Yes. Description is defined and the Firebase (Firestore server) value is getted as expected and putted inside the markdown editor. But when I introduce any change in the editor that change does not succeed in the variable.
