### ISSUE TITLE
Why it want jquery?

### ISSUE THREAD

**Issue by paulvonber** [nasa8x/v-markdown-editor#6]
Is this editor depending on jQuery???
![image](https://user-images.githubusercontent.com/37245111/75859532-77b85e00-5dfa-11ea-9e54-05acf6b53686.png)

**Comment by nasa8x** [comment]
Using a bit of bootstrap, I will remove jQuery the next time I update.

**Comment by jonathanpmartins** [comment]
@nasa8x  you can use BootstrapVue -> https://bootstrap-vue.js.org/ for bootstrap stuff.
